### PR TITLE
ansible testing with molecule

### PR DESCRIPTION
**Pull request by harshavmb**
In this tutorial, we will unit test `ansible` with `molecule` framework on `Hetzner` infrastructure. 

I have read and understood the Contributor's Certificate of Origin available at the end of
https://raw.githubusercontent.com/hetzneronline/community-content/master/tutorial-template.md
and I hereby certify that I meet the contribution criteria described in it.
Signed-off-by: [Harshavardhan Musanalli and email address [harshavmb@gmail.com](mailto:harshavmb@gmail.com)]

### CODE REVIEW

**Comment by svenja11** [comment]
Thank you for your contribution @harshavmb! I read through your tutorial and I made some updates, including:

* I made some formatting updates
* I added an example task for `os_hardening_rule`. The idea is that everyone can follow the tutorial even if they haven't created any rules before.
* I changed the order of the YAML files to the order in which they would be run by Ansible so that it is easier to explain them step-by-step.
* I removed your explanation in the `molecule.yml` file and added it in a table below to make the YAML file more clear.

Please let me know what you think.

**Important:** It looks like some of your text is copy&paste (e.g. [Ansible docs](https://ansible.readthedocs.io/projects/molecule/getting-started/)). Please note that we have very strict rules regarding duplicated content (see [Contribution Guidelines » Content](https://github.com/hetzneronline/community-content/blob/master/contributing.md#content))
Please update your content and make sure it is completely written by you. Otherwise, I cannot publish this tutorial at [community.hetzner.com](https://community.hetzner.com/tutorials).

-------------------

Once the English version is final, please update the German version accordingly. Please note that the German version is currently missing the first three steps. It begins with "Step 4 - Das Scenario-Layout".

**Comment by svenja11** [comment]
@harshavmb  Do you still plan to work on this tutorial?

**Comment by harshavmb** [comment]
Hi @svenja11 , 

I was on vacation for the past few weeks. Thanks for your review. I shall work on this PR soo & ask for your re review.

**Comment by svenja11** [comment]
Thank you for updating your tutorial @harshavmb. I looked at the German version and I have a few comments:

* We decided to use "du" in all community-content tutorials. We still need to update older tutorials. However, for new tutorials we would like to already use "du". It would be great if you could update your German tutorial accordingly.

* In the beginning of the German tutorial you say "Ansible roles", in the rest of the tutorial you say "Ansible-Rollen". In the German tutorial, please change "Ansible roles" to "Ansible-Rollen" for more consistency.

* Ubuntu 24.04 just got available for Hetzner cloud servers on 25 April. It would be great if you could update the tutorial to already include the new OS.

* In "Schritt 3 - Das Scenario-Layout", you forgot to translate the text that explains <kbd>destroy.yml</kbd>. (Right above step 4)

**Comment by harshavmb** [comment]
Hi @svenja11 ,

Thanks for the feedback. I did push the changes as asked by you. 

Please perform another review. 

Thanks,
Harsha

**Pull request merged**
