### PR TITLE
Add section about 'requesting' of content / help.

### PR DESCRIPTION
**Pull request by blanky0230**
Extend README.md to guide to the Hetzner Forum or the Community-Content Issues for guidance as where to place requests for specific tutorials, request changes, and/or advice.

I have read and understood the Contributor's Certificate of Origin available at the end of 
https://raw.githubusercontent.com/hetzneronline/community-content/master/tutorial-template.md
and I hereby certify that I meet the contribution criteria described in it.
Signed-off-by: Thomas Blank blanky0230@gmail.com

### CODE REVIEW

**Comment by blanky0230** [comment]
closing https://github.com/hetzneronline/community-content/issues/61

**Comment by fdrechsler** [comment]
I like that Idea. But I would first mention the Github Issue possibility, secondly the Forum. (Since we are on Github in the README already)

**Comment by blanky0230** [comment]
@fdrechsler good point. A person being here may look at the issues first.

**Comment by fdrechsler** [comment]
Thanks Thomas.

**Pull request merged**
