### PR TITLE
Added tutorial "Deploy your own ELK stack using Docker Compose"

### PR DESCRIPTION
**Pull request by Blue25GD**
I have read and understood the Contributor's Certificate of Origin available at the end of 
https://raw.githubusercontent.com/hetzneronline/community-content/master/tutorial-template.md
and I hereby certify that I meet the contribution criteria described in it.
Signed-off-by: Alexandru Popescu (alexandru.popescu.fr@icloud.com)

### CODE REVIEW

**Comment by svenja11** [comment]
Thank you for your contribution @Blue25GD! I read through your tutorial and I made some updates, including:

* You introduction was very brief, so I added a little bit more information.

* I updated the terminology section to match the [example tutorial](https://github.com/hetzneronline/community-content/blob/master/tutorial-template.md), which suggests to use `holu` and `<your_host>`.

* If you really want to add the output, you should do it with a code block instead of the screenshots:
  ```shellsession
  [+] Running 3/3
   ✔ Container kibana           Started
   ✔ Container setup            Started
   ✔ Container elasticsearch    Started
  ```
  In some cases I actually don't think you need them at all, so I simply removed those completely.

* I put all three containers together into a single code block. You did mention that the reader has to `continue in services`, which should theoretically be enough. However, some readers can get easily confused. Putting everything in one code block, leaves less room for any confusion.

* I tested your tutorial and with the Docker Compose "kibana" line `ELASTICSEARCH_URL=http://elasticsearch:9200`, I got the following error:
  ```
  Kibana server is not ready yet.
  ```
  After I removed that line, I was able to access Kibana in the browser. For this reason, I removed the line from your tutorial.

Please let me know if the changes I made are fine with you, and I will add your tutorial to [community.hetzner.com](https://community.hetzner.com/tutorials).

**Comment by Blue25GD** [comment]
Im fine with the changes, although I don't understand why ELASTICSEARCH_HOST=http://elasticsearch:9100 wouldn't work on your machine...

**Comment by ThesiiNCey** [comment]
> Im fine with the changes, although I don't understand why ELASTICSEARCH_URL=http://elasticsearch:9100 wouldn't work on your machine...

it need a matching container_name:

**Comment by Blue25GD** [comment]
Yup, I guess that's the problem. I'm ok with the changes that you made.

**Pull request merged**
