### PR TITLE
Add tutorial - Install Uptime-Kuma with Docker and Cloudflare

### PR DESCRIPTION
**Pull request by DasCanard**
```
I have read and understood the Contributor's Certificate of Origin available at the end of 
https://raw.githubusercontent.com/hetzneronline/community-content/master/tutorial-template.md
and I hereby certify that I meet the contribution criteria described in it.
Signed-off-by: Richard N. (mail@dascanard.xyz)
```

### CODE REVIEW

**Comment by DasCanard** [comment]
If everything fits, I would then also translate the whole thing into German.

**Comment by Hubi4** [comment]
Please include the following text in this pr to fulfill the [contribution guidelines](https://github.com/hetzneronline/community-content/blob/master/contributing.md#how-to).

```
I have read and understood the Contributor's Certificate of Origin available at the end of 
https://raw.githubusercontent.com/hetzneronline/community-content/master/tutorial-template.md
and I hereby certify that I meet the contribution criteria described in it.
Signed-off-by: YOUR NAME <YOUR@EMAILPROVIDER.TLD>
```

**Comment by Hubi4** [comment]
Periodically fetching the main Hetzner website is probably not the best [example](https://github.com/hetzneronline/community-content/blob/a5c763d25ee6ecb24de5b8373d566dd4abc8ce71/tutorials/deploy-uptime-kuma-with-docker/images/9.png).

**Comment by DasCanard** [comment]
I have read and understood the Contributor's Certificate of Origin available at the end of 
https://raw.githubusercontent.com/hetzneronline/community-content/master/tutorial-template.md
and I hereby certify that I meet the contribution criteria described in it.
Signed-off-by: Richard N. (mail@dascanard.xyz)

**Review by Hubi4 — APPROVED** [review]

**Comment by DasCanard** [comment]
Can i now start working on the german translation?

**Comment by Hubi4** [comment]
I'm just a nerdy Hetzner customer and my approval is just for my recommended changes.
@leojakeson is the person who decides which tutorial gets approved.

**Review by svenja11 — COMMENTED** [review]
Thank you for your contribution @DasCanard. I read through your tutorial and I have made a few suggetions. Feel free to modify some of my suggestions and let me know if you have any questions.

General notes:
- At https://community.hetzner.com/markdown-test-suite/, you can copy and paste your final text on the left and get a preview of your tutorial.
- The word "Uptime Kuma" does not have a hyphen.

**Comment by DasCanard** [comment]
Wow, thanks for this huge contribution to this pull request.

I really the presentation and explanations for the respective steps and I look forward to applying them to the upcoming changes.

I will do my best to implement the changes in a timely manner.

In fact, I probably saved too much on explanations in some places, so thanks again for your contribution. 😄

**Comment by DasCanard** [comment]
Wow, thanks for this huge contribution to this pull request @svenja11.

I really the presentation and explanations for the respective steps and I look forward to applying them to the upcoming changes.

I will do my best to implement the changes in a timely manner.

In fact, I probably saved too much on explanations in some places, so thanks again for your contribution. 😄

**Comment by svenja11** [comment]
@DasCanard Do you still plan to work on this tutorial?

**Comment by svenja11** [comment]
Closing as there was no activity for a very long time.  
If you find time to keep working on this tutorial in future, feel free to open a new pull request @DasCanard.

**Pull request closed without merging**
