### PR TITLE
Guide on How to Setup Remix and Mantine 

### PR DESCRIPTION
**Pull request by smyja**

### CODE REVIEW

**Comment by smyja** [comment]
I have read and understood the Contributor's Certificate of Origin available at the end of
https://raw.githubusercontent.com/hetzneronline/community-content/master/tutorial-template.md
and I hereby certify that I meet the contribution criteria described in it.
Signed-off-by: Smyja [akposlive59@gmail.com](mailto:akposlive59@gmail.com)

**Comment by svenja11** [comment]
Thank you for your contribution @smyja. In general, contributed tutorials about products with official documentation should offer additional value to the original documentation. This could be in form of some more explanations or with instructions for automated installation, for example. Your tutorial looks like you just copy&pasted all the files available at [github.com/mantinedev/remix-template](https://github.com/mantinedev/remix-template) and it does not provide this additional value. So unfortunately, it does not qualify to be published at [community.hetzner.com](https://community.hetzner.com/tutorials)

**Comment by smyja** [comment]
> Thank you for your contribution @smyja. In general, contributed tutorials about products with official documentation should offer additional value to the original documentation. This could be in form of some more explanations or with instructions for automated installation, for example. Your tutorial looks like you just copy&pasted all the files available at [github.com/mantinedev/remix-template](https://github.com/mantinedev/remix-template) and it does not provide this additional value. So unfortunately, it does not qualify to be published at [community.hetzner.com](https://community.hetzner.com/tutorials)

Can you provide an example of what you mean by additional value? I am about to write another article on setting up dokku on hetzner, what additional value should that have? Because the one for caprover doesn't provide any additional value.

**Comment by svenja11** [comment]
Please refer to our [contribution guidelines](https://github.com/hetzneronline/community-content/blob/master/contributing.md):

> Please do not just copy and paste commands and add one-line instructions. Instead, add some explanation where it's needed and provide some additional information if it's relevant.

The CapRover tutorial also includes some comments and explanation.

**Comment by smyja** [comment]
Okay 👍

**Comment by smyja** [comment]
> Please refer to our [contribution guidelines](https://github.com/hetzneronline/community-content/blob/master/contributing.md):
> 
> > Please do not just copy and paste commands and add one-line instructions. Instead, add some explanation where it's needed and provide some additional information if it's relevant.
> 
> The CapRover tutorial also includes some comments and explanation.

I am done with the dokku article https://github.com/hetzneronline/community-content/pull/773

**Pull request closed without merging**
