### PR TITLE
Added new Tutorial for an soketi-server (WebSocket-Server) behind a Reverse Proxy (nginx)

### PR DESCRIPTION
**Pull request by crocodile2024**
I have read and understood the Contributor's Certificate of Origin available at the end of 
https://raw.githubusercontent.com/hetzneronline/community-content/master/tutorial-template.md
and I hereby certify that I meet the contribution criteria described in it.
Signed-off-by: crocodile2024 < crocodile202405@gmail.com>

### CODE REVIEW

**Comment by svenja11** [comment]
Thank you for your contribution @crocodile2024!

Please note the following [contribution guidelines](https://github.com/hetzneronline/community-content/blob/master/contributing.md#language):

> If you're fluent in another language, and are able to make a translation, you can submit your tutorial in multiple languages, as long as at least one of them is English.

Before I review your tutorial, could you please confirm if you plan to add the English version too?

**Comment by crocodile2024** [comment]
Hallo,
Ja eine Englidche Version ist im Laufe der nächsten Tage geplant.

Svenja Michal ***@***.***> schrieb am Mo., 5. Aug. 2024,
14:26:

**Comment by vdbhb59** [comment]
I can translate the above one to English and give it over here. Will that make me a contributor, or.. ?

**Comment by svenja11** [comment]
Generally, we do accept translations, but translations are a lot easier to produce and far less time-consuming than actually writing a tutorial and are treated as such.

Please also note that @crocodile2024 already confirmed that they will contribute the English translation for this tutorial.

**Comment by crocodile2024** [comment]
Hello,
i have added an english version.

**Pull request merged**
