### PR TITLE
install dify on linux with automated backups

### PR DESCRIPTION
**Pull request by taowang1993**
I have read and understood the Contributor's Certificate of Origin available at the end of 
https://raw.githubusercontent.com/hetzneronline/community-content/master/tutorial-template.md
and I hereby certify that I meet the contribution criteria described in it.
Signed-off-by: Tao Wang <taowang@riverhill.ai>

### CODE REVIEW

**Comment by svenja11** [comment]
Thank you for your contribution @taowang1993!

I reviewed your tutorial and made the following changes:

* You used the sudo user to install Dify. For security reasons, this is the recommend way to do it. The cron job doesn't work if you need to enter a sudo password, so you have to use root — as you already did. However, the switch between the sudo user and root wasn't clear, so I added `sudo su`.
* You used very specific examples with Cloudflare SSL certificates and Cloudflare R2. This tutorial would also work if you used your own SSL certificate or a different S3-compatible bucket. So I added this information too.
* With restic, you have to set a password. If you run the script manually, you can enter the password yourself. If the cron job doesn't know the password, it will fail, so I added the password to the script via `RESTIC_PASSWORD_FILE`.

With those changes, the tutorial looks good to me now.

**Comment by svenja11** [comment]
Helllo @taowang1993, I tried to contact you via email regarding your credits but it seems the email could not get delivered. Did you provide a correct email address?

**Comment by taowang1993** [comment]
Hi Svenja Michal,

I received your emails regarding the content changes and updates.

However, I did not receive emails regarding the credits.

What are the next steps to receive the credits?

Thank you

Tao Wang

**Comment by taowang1993** [comment]
Hi Svenja,

I just updated my email address to ***@***.***

It seems like the ***@***.*** email address is having some issues
currently.

Tao Wang

**Pull request merged**
