### PR TITLE
Added note to routed vmbr in proxmox tutorial

### PR DESCRIPTION
**Pull request by TomSDEVSN**
Added a note to routed vmbr in proxmox tutorial so that a "DAU" is not using the same ipv6 address as on eth0.

### CODE REVIEW

**Comment by n-se** [comment]
It actually can be the same as on eth0, on eth0 is /128

**Comment by TomSDEVSN** [comment]
Due open PR I wasn't able to create a new PR for the tutorial.

**Comment by philwo** [comment]
Could someone explain why this change was made?

@rook59 wrote above that the `vmbr0` can have the same IPv6 address as the `eth0` device. I tested this configuration and it works fine, I cannot observe any issues with it.

I'm not saying that this change was wrong, but I would like to understand why we need to use a different IPv6 address on the `vmbr0` device. :)

**Comment by philwo** [comment]
This also contradicts the Hetzner documentation for "Additional IP addresses" which says that you can use the same IPv6 address on the physical device with a `/128` prefix and the bridge with a `/64` prefix:

image

https://docs.hetzner.com/robot/dedicated-server/ip/additional-ip-adresses/#individual-addresses

**Pull request merged**
