### PR TITLE
How To Install Git on Ubuntu 18.04

### PR DESCRIPTION
**Pull request by Tumite**
I have read and understood the Contributor's Certificate of Origin available at the end of 
https://raw.githubusercontent.com/hetzneronline/community-content/master/tutorial-template.md
and I hereby certify that I meet the contribution criteria described in it.
Signed-off-by: Roland Balla <balla.roland96@gmail.com>

### CODE REVIEW

**Comment by n-se** [comment]
This tutorial seems to be partly copied from https://www.digitalocean.com/community/tutorials/how-to-install-git-on-ubuntu-18-04
@Tumite please re-read the Contributor's Certificate of Origin and edit your tutorial

**Comment by Tumite** [comment]
The DO tutorial does not work. My tutorial work. I don’t know what is the problem, i just take the structure.

**Comment by n-se** [comment]
We have seen that you have changed a few things but it is way to similar. A lot of the text is copied from DO. Due to a recent incidient https://github.com/hetzneronline/community-content/pull/184 we need to be more strict on this.

You can keep the structures, but please modify the text and descriptions. If we paste both tutorials in a diff viewer they are too identical.

**Comment by Tumite** [comment]
Okay, i understand. I tried to change, you can check.

**Pull request merged**
