### PR TITLE
How to install your own Matrix Synapse server and Element Messenger

### PR DESCRIPTION
**Pull request by LamaImPyjama**
I have read and understood the Contributor's Certificate of Origin available at the end of 
https://raw.githubusercontent.com/hetzneronline/community-content/master/tutorial-template.md
and I hereby certify that I meet the contribution criteria described in it.
Signed-off-by: Claus - git@fidela.at

### CODE REVIEW

**Review by tomsiewert — CHANGES_REQUESTED** [review]

**Comment by svenja11** [comment]
@LamaImPyjama  Do you still plan to work on this tutorial?

**Comment by LamaImPyjama** [comment]
@svenja11 Yes, haven't noticed your comments. Give me a few days.

**Comment by svenja11** [comment]
@LamaImPyjama Do you still plan to work on this tutorial?

**Comment by svenja11** [comment]
Closing as there was no activity for a very long time.
If you find time to keep working on this tutorial in future, feel free to open a new pull request @LamaImPyjama.

**Pull request closed without merging**
