### PR TITLE
Tutorial: How To Install ISPConfig on Ubuntu 20.04 LTS

### PR DESCRIPTION
**Pull request by azadshaikh**
There are very few tutorials on ISPConfig. I think this tutorial is a perfect fit for Hetzner Community. 

I have read and understood the Contributor's Certificate of Origin available at the end of 
https://raw.githubusercontent.com/hetzneronline/community-content/master/tutorial-template.md
and I hereby certify that I meet the contribution criteria described in it.

Signed-off-by: Azad Shaikh <mohd.azad.shaikh@gmail.com>

### CODE REVIEW

**Review by rook59 — APPROVED** [review]

**Comment by rook59** [comment]
@azadshaikh do you need another review? Or was that by mistake?

**Comment by azadshaikh** [comment]
I am sorry by mistake.

**Comment by leojakeson** [comment]
Please add the Contributor's Certificate of Origin to the end of your tutorial and sign it, then we can merge the tutorial.

**Comment by azadshaikh** [comment]
> Please add the Contributor's Certificate of Origin to the end of your tutorial and sign it, then we can merge the tutorial.

Done.

**Pull request merged**
