### PR TITLE
Tutorial for creating secure Ubuntu 18.04 image

### PR DESCRIPTION
**Pull request by rericsson**
Hi,
I've written a draft of a tutorial that shows how to create an Ubuntu snapshot that meets the DevSec Linux Baseline specification. I hope it meets your requirements and look forward to any comments to improve the content. 

I have read and understood the Contributor's Certificate of Origin available at the end of 
https://raw.githubusercontent.com/hetzneronline/community-content/master/tutorial-template.md
and I hereby certify that I meet the contribution criteria described in it.
Signed-off-by: Robert Ericsson <rob@l10systems.com>

### CODE REVIEW

**Comment by n-se** [comment]
Thank you for this tutorial! I saw you included also an already submitted one. Can you please remove this tutorial and only submit your new changes?

**Comment by rericsson** [comment]
Hi,
Sorry for the confusion. I'm not sure how to remove the extra commits from the PR. I may have done it in the last commits but I still see the old ones in the PR. Should I close this PR and create a new one with just the new tutorial? 

Thanks.
Rob

**Comment by n-se** [comment]
> Should I close this PR and create a new one with just the new tutorial?

If you don't know how you drop the other commits via git on command line, closing this and opening a new PR is probably the best way. :)

**Comment by rericsson** [comment]
OK. I'll close the PR and create a new one. I know how to remove commits from a normal repo but that doesn't seem to work on a forked repo.

**Pull request closed without merging**
