### PR TITLE
Additional IP Addresses SUSE

### PR DESCRIPTION
**Pull request by MakusShoebird**

### CODE REVIEW

**Comment by blanky0230** [comment]
Would you mind to give more descriptive names to the pull requests and commit messages?

After some insertions it's hard to track back WHAT and WHY things are added here imho.

For Example this pull request could have the same name as your branch: `additional-ip-addresses-suse`

And your commit-message could be as simple as "Import article "Zusaetzliche IP-Adressen fuer Suse-Linux" from Hetzner Wiki"

I think this would have several benefits for the history of this project as well as tractability of the changes made.

**Comment by blanky0230** [comment]
My comment above also applies to the numerous other PRs you've opened :)

**Comment by n-se** [comment]
I think, "Import article" is not needed because the pull request already has labels for that

**Comment by leojakeson** [comment]
Meant for docs, not community tutorial

**Pull request closed without merging**
