### PR TITLE
Lsi raid controller

### PR DESCRIPTION
**Pull request by MakusShoebird**

### CODE REVIEW

**Comment by asciiprod** [comment]
Please refer to the Guidelines. Only original work will be accepted.

**Comment by asciiprod** [comment]
this article needs to be rewritten to large degree to make use of storcli, as megacli has been deprecated some years ago. (nevertheless is still works on older controllers)

**Comment by fdrechsler** [comment]
Okay, do you think it could be relevant to keep it in that state and rework it later? If not, i think we should revert.

**Comment by asciiprod** [comment]
Well, it is not wrong, but it needs work. At least rename it "How to configure an Broadcom/Avago/LSI RAID Controller" (yeah, the company got sold a couple of times)

**Pull request merged**
