### PR TITLE
First Install Caddy with PHP8.2 and MariaDB 10.11.5

### PR DESCRIPTION
**Pull request by Lauras-Universe**
I have read and understood the Contributor's Certificate of Origin available at the end of 
https://raw.githubusercontent.com/hetzneronline/community-content/master/tutorial-template.md
and I hereby certify that I meet the contribution criteria described in it.
Signed-off-by: Laura-Lea <mailbox@lauras-universe.de>

### CODE REVIEW

**Comment by svenja11** [comment]
@Lauras-Universe This does not look like a complete tutorial. Do you still plan to work on this?

**Comment by Lauras-Universe** [comment]
Why doesn't this look like a tutorial, what do they think is missing. It is a tutorial on how to install this and then host websites on it.

**Comment by svenja11** [comment]
Please refer to our contribution guidelines and our tutorial template:
* [Contribution guidelines](https://github.com/hetzneronline/community-content/blob/master/contributing.md)
* [Tutorial template](https://github.com/hetzneronline/community-content/blob/master/tutorial-template.de.md)

The tutorial you submitted does not follow the standard layout explained in the example tutorial. And for most of the steps, you did not add any explanation. Please note this quote from the contribution guidelines:

> The tutorial should provide value to the reader. Please **do not just copy and paste commands and add one-line instructions**. Instead, add some explanation where it's needed and provide some additional information if it's relevant.

**Comment by Lauras-Universe** [comment]
Are you someone who decides whether this is recorded or not?

**Comment by Lauras-Universe** [comment]
Is this required to use the template layout to 100%?

**Comment by Lauras-Universe** [comment]
And can i use Tables in the Tutorial?

**Comment by Lauras-Universe** [comment]
Now i get a update i hope this is perfect to use.

**Comment by svenja11** [comment]
This tutorial is still very brief and basic. For most of the steps, you did not add any explanation (please see the quote from our [contribution guidelines](https://github.com/hetzneronline/community-content/blob/master/contributing.md#general-criteria) below). In general, contributed tutorials should have more content and be more in-depth. So unfortunately, this tutorial does not qualify to be published at community.hetzner.com.

Quote from out [contribution guidelines](https://github.com/hetzneronline/community-content/blob/master/contributing.md#general-criteria):

> Please **do not just copy and paste commands and add one-line instructions.** Instead, add some explanation where it's needed and provide some additional information if it's relevant.

**Pull request closed without merging**
