### PR TITLE
v202030918 Initial version

### PR DESCRIPTION
**Pull request by tootai**
I have read and understood the Contributor's Certificate of Origin available at the end of https://raw.githubusercontent.com/hetzneronline/community-content/master/tutorial-template.md and I hereby certify that I meet the contribution criteria described in it.
Signed-off-by: Daniel Huhardeaux <devel@tootai.net>

### CODE REVIEW

**Comment by svenja11** [comment]
@tootai This does not look like a complete tutorial. Do you still plan to work on this?

**Comment by tootai** [comment]
What kind of information should be added ?

**Comment by svenja11** [comment]
Please refer to our contribution guidelines and our tutorial template:

* [Contribution guidelines](https://github.com/hetzneronline/community-content/blob/master/contributing.md)
* [Tutorial template](https://github.com/hetzneronline/community-content/blob/master/tutorial-template.de.md)

--------------

* **Prerequisites**
  
  > If there is already a tutorial explaining one of the prerequisites, make sure to link to that other tutorial. (Quote from tutorial template)
  
  Please list each prerequisite as a single bullet point. As mentioned in the tutorial template, it would be great if you could check if there are any tutorials available that you could link to. Or maybe just link to the official website. You could also add a brief explanation if needed.
  
  <details>
  
  <summary>Example 1</summary>
  
  **Prerequisites**
  
  * **Hetzner Cloud API token**<br>
    If you don't have an API token yet, you can check out the getting started [How to generate an API token](https://docs.hetzner.com/cloud/api/getting-started/generating-api-token)
  
  * **SSH access to your server**<br>
    For more information on how to connect to a server via SSH, you can check out one of these tutorials:
    * [Establishing an SSH connection from Windows](https://community.hetzner.com/tutorials/howto-ssh-on-windows)
    * [Connecting to your Server](https://docs.hetzner.com/cloud/servers/getting-started/connecting-to-the-server)
  
  * **curl installed**<br>
    You can run `curl --version` in your terminal to check if curl is installed. If it is not installed, you can download it here: [curl.se/download.html](https://curl.se/download.html)
  
  * [Add more prerequisites as needed]
  
  </details>
  
  <details>
  
  <summary>Example 2</summary>
  
  **Prerequisites**
  
  * Hetzner Cloud [API token](https://docs.hetzner.com/cloud/api/getting-started/generating-api-token) in the [Cloud Console](https://console.hetzner.cloud/)
  * SSH access to your server (e.g. from [Windows](https://community.hetzner.com/tutorials/howto-ssh-on-windows) / [Linux](https://docs.hetzner.com/cloud/servers/getting-started/connecting-to-the-server))
  * [curl](https://curl.se/download.html) installed
  * [Add more prerequisites as needed]
  
  </details>

<br>

* **Steps**<br>
  > These tutorials will be read by users with a wide range of experience. Make sure beginners can still follow what is being done. This means it is important **not to skip any steps, no matter how obvious or self-explanatory they may seem.** (Quote from contribution guidelines)
  
  At the moment, you just jump right into it with hardly any explanation. It would be great if you could explain every step starting from the very beginning (e.g. create a new file, copy&paste the script, where you need to replace placeholders with your own server information).

<br>

* **Script**<br>
  Please note that everything needs to be in the `01.en.md` and `01.fr.md` files. This means that you can't keep the script in a separate file. Reason for this is that other files are not shown at [community.hetzner.com](https://community.hetzner.com/tutorials). So if someone tried to follow your tutorial, they would not have the script. So please delete the `hzvs.sh` file and add the script in your `01.en.md` and `01.fr.md` files.
  
  <br>
  
  The script is obviously quite long, so my suggestion would be to use `details`.
  This would look like this:
  
  <details>

  <summary>Click here to view the script</summary>
  
  ```sh
  #!/bin/bash
  #
  #   On the server, the user which is login using ssh MUST have the right to shutdown via sudo
  
  [...]
  
  else
    echo "API key NOT existing, please verify server parameters <$1>"
  fi
  
  exit 0
  ```
  
  </details>
  
  You can use `<details>` like this:
  ``````sh
  <details>
  
  <summary>Click here to view the script</summary>
  
  ```sh
  #!/bin/bash
  #
  #   On the server, the user which is login using ssh MUST have the right to shutdown via sudo
  
  [...]
  
  else
    echo "API key NOT existing, please verify server parameters <$1>"
  fi
  
  exit 0
  ```
  
  </details>
  ``````
  
  You can enter your text in our [Markdown Preview](https://community.hetzner.com/markdown-test-suite/) to see how it would look on the website.

<br><br>

On another note, I feel like the purpose of your script is similar to the use of the official [Hetzner Cloud command-line interface](https://github.com/hetznercloud/cli#hcloud-command-line-interface-for-hetzner-cloud) (e.g. `hzvs.sh <your-server-name> on` and `hcloud server poweron <your-server-name>`). Maybe it's worth mentioning the advantage of your script.

**Comment by svenja11** [comment]
@tootai Do you still plan to work on this tutorial?

**Comment by svenja11** [comment]
Closing as there was no activity for a long time.
If you find time to keep working on this tutorial in future, feel free to open a new pull request.

**Pull request closed without merging**
