### PR TITLE
Configure subnet Hetzner tutorial pull request

### PR DESCRIPTION
**Pull request by sniperkitten**
I have read and understood the Contributor's Certificate of Origin available at the end of 
https://raw.githubusercontent.com/hetzneronline/community-content/master/tutorial-template.md
and I hereby certify that I meet the contribution criteria described in it.
Signed-off-by: Alexander Pavlik <alexander.pavlik@enginatics.com>

### CODE REVIEW

**Comment by n-se** [comment]
Maybe a duplicate of #81, please inspect this @leojakeson

**Comment by leojakeson** [comment]
@sniperkitten Thanks for the pull request, but this is too short and not detailed enough to be added as a tutorial, sorry.

**Comment by sniperkitten** [comment]
Hello,

np, just wanted to share solution to a problem that many customers might
face potentially
Hope to see it in other tutorial or on Hetzner wiki

Regards,
Alex

**Comment by n-se** [comment]
If you add some more information and details I am sure you can create a good tutorial here too.

**Pull request closed without merging**
