### PR TITLE
[Mailcow] Update to current state, remove malicious link and added new topics

### LINKED ISSUE #497: Setup your own mail server with Mailcow
## Add missing information
Please specify what server we should choose for this project... what server will fit the needs for this install.

### PR DESCRIPTION
**Pull request by kev-ac**
This commit updates the tutorial to the current state (OS, Docker), removes a link to a malicious site and adds the topic Backups and enhances information about updates.

Also fixes #497.

I have read and understood the Contributor's Certificate of Origin available at the end of 
https://raw.githubusercontent.com/hetzneronline/community-content/master/tutorial-template.md
and I hereby certify that I meet the contribution criteria described in it.
Signed-off-by: kev-ac <oss@thiefes.de>

### CODE REVIEW

**Comment by biberairport** [comment]
@svenja11 Looks good to me, can be merged. 🐕

**Review by kev-ac — COMMENTED** [review]
Looks good to me 👍

**Comment by svenja11** [comment]
Thank you for your contribution @kev-ac! Please add the license block at the bottom of the English file and sign off, and I will merge it.

```
##### License: MIT

<!--

Contributor's Certificate of Origin

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I have
    the right to submit it under the license indicated in the file; or

(b) The contribution is based upon previous work that, to the best of my
    knowledge, is covered under an appropriate license and I have the
    right under that license to submit that work with modifications,
    whether created in whole or in part by me, under the same license
    (unless I am permitted to submit under a different license), as
    indicated in the file; or

(c) The contribution was provided directly to me by some other person
    who certified (a), (b) or (c) and I have not modified it.

(d) I understand and agree that this project and the contribution are
    public and that a record of the contribution (including all personal
    information I submit with it, including my sign-off) is maintained
    indefinitely and may be redistributed consistent with this project
    or the license(s) involved.

Signed-off-by: [submitter's name and email address here]

-->
```

**Comment by kev-ac** [comment]
@svenja11 I've added the block to the file.

**Comment by kev-ac** [comment]
@svenja11 I've created one more PR right now to remove the dodgy link from the russian version of this tutorial in #553.
Contentwise nothing has changed there.

**Pull request merged**
