### PR TITLE
New tutorial: custom os images with packer

### PR DESCRIPTION
**Pull request by hegerdes**
I added a new atricle that describes how users can use the `hcloud` Packer provider to create custom images.

Feel free to add feedback.

*Note:* If this article is accepted I am willing to provide a german version. But I want to have a commitment before I do the extra work

I have read and understood the Contributor's Certificate of Origin available at the end of
https://raw.githubusercontent.com/hetzneronline/community-content/master/tutorial-template.md
and I hereby certify that I meet the contribution criteria described in it.
Signed-off-by: Henrik Gerdes (hegerdes[at]outlook.de)

### CODE REVIEW

**Review by svenja11 — COMMENTED** [review]
Thank you for your contribution @hegerdes! I read through your tutorial and I made some changes and suggestions. Please let me know if those are fine with you. I had to edit the description at the top because it can't be longer than 160 characters. Other than that, your tutorial looks good now and you can add the German translation if you want. 🙂

------------

In your pull request, please add the following comment and remember to replace `[submitter's name and email address here]` with your own information.

> I have read and understood the Contributor's Certificate of Origin available at the end of
https://raw.githubusercontent.com/hetzneronline/community-content/master/tutorial-template.md
and I hereby certify that I meet the contribution criteria described in it.
Signed-off-by: [submitter's name and email address here]

**Comment by svenja11** [comment]
Regarding the link, that's fine then, I'll make an exeption. You won't need to add the code to this repo.

And I will make a note of your syntax highlighting request.

**Comment by hegerdes** [comment]
Done - maybe it is a good idea too add that text into GHs PR-Template

**Comment by svenja11** [comment]
Thank you!

The statement is given in the final step in our [contribution guidelines](https://github.com/hetzneronline/community-content/blob/master/contributing.md#how-to-contribute-step-by-step).

**Pull request merged**
