### PR TITLE
Add a DiscordJS bot tutorial

### PR DESCRIPTION
**Pull request by Wqrld**
Would there be interest in this? 
(not done, I will finish it if there is interest.)

Hetzner is a great way to host discord bots. I often get the question where you should host a discord bot and I have been using hetzner for years to host my own bots but its a bit harder on a VPS that just with a shared hosting provider that often charge way more than needed.

### CODE REVIEW

**Comment by n-se** [comment]
We are open to almost any tutorial. I mean such a tutorial fits perfectly. You install some software, configure this and that - and have a nice bot ;)

**Comment by n-se** [comment]
Hi @Wqrld, do you still plan to write this tutorial?

**Comment by Wqrld** [comment]
I do, looks like I fully forgot about this, I will continue soon

Op do 16 apr. 2020 08:59 schreef Noah Seefried <notifications@github.com>:

**Comment by n-se** [comment]
Any update?

**Comment by Wqrld** [comment]
closing for now as i haven't had the time yet, will reopen when i can start again.

**Pull request closed without merging**
