### PR TITLE
Dockerizing MariaDB with Alpine Linux

### PR DESCRIPTION
**Pull request by mrgharabaghi**
This tutorial is split into multiple parts.

1. Dockerizing MariaDB with Alpine Linux
2. Import and Export data in Dockerized MariaDB
3. Connect to Dockerized MariaDB with Node.js via Unix socket

> I have read and understood the Contributor's Certificate of Origin available at the end of 
> https://raw.githubusercontent.com/hetzneronline/community-content/master/tutorial-template.md
> and I hereby certify that I meet the contribution criteria described in it.
> Signed-off-by: Reza Gharabaghi oqabemail@gmail.com

### CODE REVIEW

**Comment by mrgharabaghi** [comment]
Is there a problem? What should I do? @svenja11

**Comment by svenja11** [comment]
`review wanted` just means that someone from the Hetzner team should proofread the tutorial. Once we checked the tutorial, we will let you know if there's anything you need to do. If everything is fine, we will publish it directly. :)

**Comment by mrgharabaghi** [comment]
@svenja11 Long time no see!

**Comment by svenja11** [comment]
Sorry for the delay! Unfortunately, there are currently not enough Community Managers but I will make sure to review your tutorial first thing tomorrow!

**Comment by svenja11** [comment]
I just went through your tutorial and it looks good to me know. Thank you for you contribution @mrgharabaghi!

Please add the license block at the bottom of each file (`01.en.md`, `02.en.md`, `03.en.md`) and I will mark this PR as ready:

Remember to replace `[submitter's name and email address here]` with your own information.

```
##### License: MIT

<!--

Contributor's Certificate of Origin

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I have
    the right to submit it under the license indicated in the file; or

(b) The contribution is based upon previous work that, to the best of my
    knowledge, is covered under an appropriate license and I have the
    right under that license to submit that work with modifications,
    whether created in whole or in part by me, under the same license
    (unless I am permitted to submit under a different license), as
    indicated in the file; or

(c) The contribution was provided directly to me by some other person
    who certified (a), (b) or (c) and I have not modified it.

(d) I understand and agree that this project and the contribution are
    public and that a record of the contribution (including all personal
    information I submit with it, including my sign-off) is maintained
    indefinitely and may be redistributed consistent with this project
    or the license(s) involved.

Signed-off-by: [submitter's name and email address here]

-->
```

**Comment by mrgharabaghi** [comment]
Done @svenja11

**Comment by mrgharabaghi** [comment]
@svenja11 
You forgot to add `Existing tutorial` tag to this issue.

**Comment by svenja11** [comment]
We usually add the label `Existing tutorial`, when changes are made to an existing file (e.g. [#977](https://github.com/hetzneronline/community-content/pull/977/files)). This was a new tutorial.

**Pull request merged**
